services:
  app:
    build:
      dockerfile: "WebApi/Dockerfile"
      args:
        PRODUCT_VERSION: "1.0.0"
    depends_on:
      - dynamodb
    ports:
      - 3000:3000
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:3000"
      DOTNET_ReadyToRun: 0
      DOTNET_TC_QuickJitForLoops: 1
      DOTNET_TieredCompilation: 1
      DOTNET_TieredPGO: 1
      DOTNET_gcServer: 1
      DOTNET_GCDynamicAdaptationMode: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      ConnectionStrings__DynamoDb: "http://dynamodb:8000"

  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - 5434:8000
